name: SkippyMart

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::824333227939:role/skippymart
          aws-region: us-west-2

      - name: List S3 buckets
        env:
          AWS_REGION: us-west-2
        run: |
          aws s3 ls
          